[package]
name = "nixcbs"
version = "0.1.0"
edition = "2024"

[dependencies]
pretty_env_logger = "0.5"
log = "0.4"
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"